### ISSUE TITLE
Wrong answer on multiple test cases!!

### ISSUE THREAD

**Issue by AKACHI-4** [AKACHI-4/JAVA-DSA#10]
#9 commit needs modification as it is wrong somewhere in the between and showing an error for edge cases.

**Comment by LordBurtz** [comment]
What is the problem? What edge case is not solved?

**Comment by AKACHI-4** [comment]
actually pivot index is not getting right for some cases as I apply the wrong condition to find the pivot there ... now I got it.
.
but if you want to make a good change somewhere so feel free to do so

**Comment by AKACHI-4** [comment]
PR was generated for this issue and it merged soon.
